# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Terraspin < Formula
  desc "Terraform plan risk analysis — understand your infrastructure changes before you apply"
  homepage "https://github.com/terraspin/terraspin"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/terraspin/terraspin/releases/download/v0.1.0/terraspin_0.1.0_darwin_amd64.tar.gz"
      sha256 "1e9e5611b7743cfb5b52b66462129e6a8d224d8b530cf6995842de7c1cd95914"

      define_method(:install) do
        bin.install "terraspin"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/terraspin/terraspin/releases/download/v0.1.0/terraspin_0.1.0_darwin_arm64.tar.gz"
      sha256 "75cfa64565f882443bb19968d267e19582e2de2597f5fcba6dc360cbcef1fd6d"

      define_method(:install) do
        bin.install "terraspin"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/terraspin/terraspin/releases/download/v0.1.0/terraspin_0.1.0_linux_amd64.tar.gz"
      sha256 "cf1f9ae2e62dd139e1fba392174d97ae4525c676945e3e95e0f38d421b7790d3"
      define_method(:install) do
        bin.install "terraspin"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/terraspin/terraspin/releases/download/v0.1.0/terraspin_0.1.0_linux_arm64.tar.gz"
      sha256 "90dbd64f1c241804a27ded1b86f4c1c8a3b4a29824d07f7ef8354a25388e75dd"
      define_method(:install) do
        bin.install "terraspin"
      end
    end
  end

  test do
    system "#{bin}/terraspin version"
  end
end
